### PR TITLE
Upgrade to Bootstrap 3

### PR DESCRIPTION
**Pull request by christianbundy**
> Upgraded to support Bootstrap 3. Might not be comprehensive, and drops
> support for Bootstrap 2. Maybe fit for a separate branch?

I'm putting this on the [bootstrap-3](https://github.com/christianbundy/jsonform/tree/bootstrap-3) branch.

### CODE REVIEW

**Comment by nickl-** [comment]
@christianbundy, kudos for taking initiative you rock! 

This feels odd though please would you open the issues for us too. If there are no maintainers over at [joshfire/jsonform](/joshfire/jsonform) then there is no one to maintain the issues either and even worse than unmerged PRs is the harm caused by unattended issues...

I left this comment related to this patch at https://github.com/joshfire/jsonform/issues/94 and foresaw the predicament @kimsey0 refers to, that it requires a separate branch and all the ball ache that entails. Since we have both implementations now (bs2 and bs3) is it not evident where the commonalities are and what needs to be abstracted. Before they run too far apart I would like to see the two branches merge again while retaining support for both bootstrap 2 and bootstrap 3. While at the same time create the boilerplate by which you can customize the rendered output in your own project or adapt to another framework without having to split form away from upstream in the process.

### Zen and the art of concern abstraction

May I suggest that we decouple the templates or incorporate namespacing to allow for multiple frameworks/output while retaining the update path for subsequent releases of jsonform core and other fixes.

Surely there are zurb, jq ui, blueprint, ionic, gridlock, etc, etc and even more amazing frameworks enough to justify us looking beyond the horizon of mere bootstrap 3 enablement as the adaptability becomes ever more pertinent.

For those who haven't realised yet, there is no smooth transition from what was then BS2 to what is now BS3 some might even argue that the only thing they have in common is in the name. IMHO forget about sacrificing BS2 in favour of BS3 (or postponing the inevitable) it's futile... instead lets find the equilibrium which welcomes both (and others) which helps us remain sane. =)

Not to be the devils advocate but maybe it's become time to consider an alternative templating solution. I have no qualms with underscores' implementation per se but its strength in simplicity is starting to show as weakness. Perhaps something with template inheritance will better suite (especially for the likes of input type=text and friends) and simultaneously reduce the learning curve of initial adoption through a simplified and intuitive approach.

I believe there are solutions which may be pre-compiled/rendered into equally optimised and obfuscated form so as not to require a sacrifice for obtaining a more pleasurably maintainable codebase either.

Just saying... this is the golden opportunity, right?

**Comment by christianbundy** [comment]
Thanks for the suggestion, I didn't realize issues were disabled but I've enabled them now. Personally, I think that jsonform would benefit from a rewrite. On my last client project I actually wrote my own JSON to form parser because this one is too opinionated and pushes the developer into a corner.

I eventually wrote it with lodash and a Handlebars template, and it was _much_ easier to use than this project. I agree that this is the golden opportunity – did you have any specific suggestions on the way it's written? I'd love to get more of your input.

**Comment by steve-m-brown** [comment]
Have a look at https://github.com/jdorn/json-editor - fewer features, but more current and less opinionated

**Comment by christianbundy** [comment]
@steve-m-brown Wow, that's incredibly similar to how I wrote my implementation in my comment above. I dig it – I'll check it out this weekend.

**Comment by steve-m-brown** [comment]
I'll be very interested in your opinion - I'm looking for something to make wire-framing UIs easier, and JSON schema feels like part of the answer. json-editor appeals because of its support for multiple CSS frameworks - and templating engines, which suggests it's built from the ground up to be extensible.

**Comment by nickl-** [comment]
@steve-m-brown it was for exactly this purpose that I was motivated to keep json-schema alive, its ability to describe user input. Sure validation is novel but who needs to validate a number when you edit it with an `input type="number"` field. I was slightly disappointed when I saw jsonform did not "actually" support the "official" schema, but not as much as when I heard the verdict from @christianbundy. 

Been watching the project from a distance for some time now and you'd think, based on the amount of chatter that... well... I guess you can't judge a project by its chatter.

JSON Editor is new to me... like what I am seeing =)
I only hope it's not  bootstrap-json-editor... lets see

Some other related projects:
onde - showed great potential but is currently abandoned/dormant http://exavolt.github.io/onde/#?schema_url=schemas/jquery-package.json
re:form.ed - also good potential but remained under exposed  http://bigbluehat.github.io/reformed/
JSONwidget - very much outdated and abandoned
http://jsonwidget.org/example.php?sample=normal&user=advanced
Jsonary - well... never could quite understand what this guy is trying to accomplish, http://jsonary.com/demos/index-input.html

Slightly off topic:
Schema generator has some interesting forms - http://www.jsonschema.net/index.html

**Comment by steve-m-brown** [comment]
@nickl- thanks for these links. I wonder why nothing like these has gained critical mass. Maybe it's just JSON's being a reaction against anything that smacks of XML ceremony (I still have nightmares about XML Schema). Kudos to json-schema for making (and keeping) it so simple.

JSON Editor does at least seem to support multiple CSS frameworks (bootstrap 2 and 3, foundation 3-5, query ui) - and I'm kind of hoping @christianbundy will find it well enough structured to support bolting on any framework you like. Or none at all. POSH would be nice.

**Comment by nickl-** [comment]
I'm liking JSON Editor a lot! =)

I don't know why the generation advantages of meta information is not as popular as validation, I mean how many different ways is there to validate data?  Especially based on meta data all it does is say yeah or neah you still have to do the other parts like presenting the errors to the user.  

Matic is also worth mentioning https://github.com/mattyod/matic which generates documentation from the meta data.

**Pull request closed without merging**
